# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fff005ba6f9b75c59789fee06233c19d48b38a990775e1e361ae5f27330f61c319c41d3e8123015506a65180bbee458a21978a381afa78a41d764ece84cb2da0

test:
  secret_key_base: 651407fd4061451afeb0d3392a703e4f4b8e4961e27e9694e7818865b3c220877ffbca0592485c761aeaf3a5737d7ec83a6933d948a4c202b926636f110943a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
